//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEvents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventContainer : DbContext
    {
        public EventContainer()
            : base("name=EventContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<FederalDistricts> FederalDistricts { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<MessageStatuses> MessageStatuses { get; set; }
        public virtual DbSet<PopularGroups> PopularGroups { get; set; }
        public virtual DbSet<PopularMessages> PopularMessages { get; set; }
        public virtual DbSet<Processing> Processing { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffEvents> StaffEvents { get; set; }
        public virtual DbSet<StaffTypes> StaffTypes { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
