//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEvents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processing
    {
        public int IdProcessing { get; set; }
        public int IdStaff { get; set; }
        public int IdMessage { get; set; }
        public int IdMessageStatus { get; set; }
        public string AnswerComment { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual MessageStatuses MessageStatuses { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
